apiVersion: v1
kind: Service
metadata:
  name: n-multi-svc
  namespace: net1
spec:
  type: NodePort
  selector:
    app: n-multi
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80
      nodePort: 30031
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 1180
      nodePort: 30032
