apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
  namespace: vol1
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: daemonset
  template:
    metadata:
      labels:
        name: daemonset
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: testlog
          mountPath: /testlogs/syslog
        - name: varlog
          mountPath: /var/log/syslog
          readOnly: true
      volumes:
      - name: testlog
        hostPath:
          path: /var/log
      - name: varlog
        hostPath:
          path: /var/log
