apiVersion: apps/v1
kind: Deployment
metadata:
  name: vol
  namespace: vol1
spec:
  selector:
    matchLabels:
      app: volume1
  replicas: 1
  template:
    metadata:
      labels:
        app: volume1
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: ['sh', '-c', 'mkdir -p /test && while true; do echo "$(date) - Write message" >> /test/test.txt; sleep 5; done']
        volumeMounts:
        - name: volume
          mountPath: /test
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: volume
          mountPath: /test
      volumes:
      - name: volume
        emptyDir: {}
